name:                aoc2025
version:             0.1.0.0
github:              "jtt9340/aoc2025"
license:             BSD-3-Clause
author:              "Joey Territo"
copyright:           "2025 Joey Territo"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:              Advent of Code 2025
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jtt9340/aoc2025#readme>

dependencies:
- base >= 4.7 && < 5
- text
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2024
default-extensions:
- MultiParamTypeClasses

library:
  source-dirs: src

executables:
  aoc2025-exe:
    main:                Main.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
    - optparse-applicative
  fmt-exe:
    main:                Fourmolu.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
    - fourmolu

tests:
  aoc2025-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Test.Days.Day0
    - Test.Days.Day1
    - Test.Util.Parsing
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
    - HUnit
  fmt-test:
    main:                Fourmolu.hs
    source-dirs:         test
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
    - fourmolu
  hlint-test:
    main:                HLint.hs
    source-dirs:         test
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlint
